apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: take2healthnetweb-claim2
  name: take2healthnetweb-claim2
spec:
  storageClassName: mount2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
