apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: take2healthnetweb-claim0
  name: take2healthnetweb-claim0
spec:
  storageClassName: mount0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
