apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: take2healthnetweb-claim1
  name: take2healthnetweb-claim1
spec:
  storageClassName: mount1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
